name: 10. Release

on:
  workflow_dispatch:
    inputs:
      release_suffix:
        description: 'Optional suffix to append to tag name (e.g., "beta", "rc1")'
        required: false
        default: ''
        type: string
      release_notes:
        description: 'Additional release notes to include in the release body'
        required: false
        default: ''
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: "10.01 Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "10.02 Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: "10.03 Configure Git"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: "10.04 Generate release date and tag"
        id: release_date
        run: |
          # Always use current date
          RELEASE_DATE=$(date +%Y-%m-%d)
          echo "date=${RELEASE_DATE}" >> $GITHUB_OUTPUT
          
          # Build tag name with optional suffix
          TAG_NAME="v${RELEASE_DATE}"
          if [ -n "${{ github.event.inputs.release_suffix }}" ]; then
            TAG_NAME="${TAG_NAME}-${{ github.event.inputs.release_suffix }}"
          fi
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: "10.05 Create or update release branch"
        run: |
          # Check if release branch exists
          if git ls-remote --heads origin release | grep -q release; then
            git checkout release
            git pull origin release
            # Remove all files except .git
            git rm -rf . || true
            git clean -fdx || true
          else
            git checkout --orphan release
          fi

      - name: "10.06 Copy files from main branch"
        run: |
          # Stash any changes to avoid checkout conflicts
          git stash || true
          
          # Switch back to main to copy files
          git checkout main
          
          # Create temporary directory to store files
          TEMP_DIR=$(mktemp -d)
          
          # Copy files to temporary directory
          cp -r src/c2puml "$TEMP_DIR/"
          cp main.py "$TEMP_DIR/"
          cp README.md "$TEMP_DIR/"
          
          # Switch back to release branch
          git checkout release
          
          # Create necessary directories
          mkdir -p src/
          
          # Copy files from temporary directory to release branch
          cp -r "$TEMP_DIR/c2puml" src/
          cp "$TEMP_DIR/main.py" .
          cp "$TEMP_DIR/README.md" .
          
          # Clean up temporary directory
          rm -rf "$TEMP_DIR"
          
          # Add all copied files
          git add .

      - name: "10.07 Verify copied files"
        run: |
          echo "📁 Verifying copied files..."
          ls -la
          echo "📁 Contents of src/:"
          ls -la src/ || echo "src/ directory not found"
          echo "📁 Contents of src/c2puml:"
          ls -la src/c2puml/ || echo "src/c2puml/ directory not found"
          echo "📄 Main files:"
          ls -la main.py README.md || echo "Some main files not found"
          echo "🔍 Git status after file operations:"
          git status

      - name: "10.08 Commit changes"
        run: |
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit, checking if files were added..."
            if [ -z "$(git status --porcelain)" ]; then
              echo "No changes detected. Creating empty commit to update release branch."
              git commit --allow-empty -m "Release ${{ steps.release_date.outputs.tag }} - $(date)"
            else
              echo "Changes detected, committing..."
              git add .
              git commit -m "Release ${{ steps.release_date.outputs.tag }} - $(date)"
            fi
          else
            echo "Staged changes detected, committing..."
            git commit -m "Release ${{ steps.release_date.outputs.tag }} - $(date)"
          fi
          git push origin release

      - name: "10.09 Create and push tag"
        run: |
          git tag -a "${{ steps.release_date.outputs.tag }}" -m "Release ${{ steps.release_date.outputs.tag }}"
          git push origin "${{ steps.release_date.outputs.tag }}"

      - name: "10.10 Create GitHub Release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_date.outputs.tag }}
          release_name: Release ${{ steps.release_date.outputs.tag }}
          body: |
            ## Release ${{ steps.release_date.outputs.tag }}
            
            This release contains:
            - C2PlantUML source code (`src/c2puml/`)
            - Main application entry point (`main.py`)
            - Documentation (`README.md`)
            
            ### Files included:
            - `src/c2puml/` - Core C2PlantUML library
            - `main.py` - Application entry point
            - `README.md` - Project documentation
            
            ${{ github.event.inputs.release_notes != '' && format('### Additional Notes\n\n{0}', github.event.inputs.release_notes) || '' }}
          draft: false
          prerelease: false