name: Convert PlantUML to JPEG

on:
  workflow_dispatch:
    inputs:
      output_folder:
        description: 'Output folder containing .puml files'
        required: false
        default: 'output'
        type: string

jobs:
  convert-puml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install PlantUML
      run: |
        echo "📦 Installing PlantUML..."
        sudo apt-get update
        sudo apt-get install -y plantuml default-jre
        
    - name: Install ImageMagick
      run: |
        echo "📦 Installing ImageMagick for JPEG conversion..."
        sudo apt-get install -y imagemagick
        
    - name: Verify installations
      run: |
        echo "🔍 Verifying installations..."
        plantuml -version
        convert -version
        
    - name: List .puml files
      run: |
        echo "📁 Listing .puml files in ${{ github.event.inputs.output_folder || 'output' }} directory:"
        find ${{ github.event.inputs.output_folder || 'output' }} -name "*.puml" -type f || echo "No .puml files found"
        
    - name: Run picgen.sh script
      run: |
        echo "🚀 Running PlantUML to JPEG conversion..."
        ./picgen.sh
        
    - name: List generated images
      run: |
        echo "📁 Generated images in output directory:"
        find output -name "*.jpg" -o -name "*.png" | sort || echo "No images found"
        
    - name: Upload generated images as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plantuml-images
        path: output/*.jpg
        retention-days: 30
        
    - name: Upload PNG files as artifacts (fallback)
      uses: actions/upload-artifact@v4
      with:
        name: plantuml-png-fallback
        path: output/*.png
        retention-days: 30
        if-no-files-found: ignore