name: Format Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        echo "🔧 Installing Python dependencies..."
        python -m pip install --upgrade pip
        echo "📦 Installing formatting tools..."
        pip install black isort flake8 pre-commit
        echo "📋 Installing package in development mode..."
        pip install -e .
        echo "✅ Dependencies installed successfully"

    - name: Show Python environment
      run: |
        echo "🐍 Python Environment Information:"
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Installed packages:"
        pip list

    - name: Check code formatting with black
      run: |
        echo "🎨 Checking code formatting with black..."
        black --check --diff .
        echo "✅ Black formatting check completed"

    - name: Check import sorting with isort
      run: |
        echo "📦 Checking import sorting with isort..."
        isort --check-only --diff .
        echo "✅ isort check completed"

    - name: Lint with flake8
      run: |
        echo "🔍 Running comprehensive flake8 linting..."
        flake8 . \
          --count \
          --show-source \
          --statistics \
          --max-line-length=88 \
          --extend-ignore=E203,W503,E501,F401,F841,W293
        echo "✅ flake8 linting completed"

    - name: Run pre-commit hooks
      run: |
        echo "🔧 Installing pre-commit hooks..."
        pre-commit install
        echo "🔍 Running pre-commit hooks..."
        pre-commit run --all-files
        echo "✅ pre-commit hooks completed"

    - name: Run custom lint script
      run: |
        echo "🚀 Running custom lint script..."
        python scripts/lint.py
        echo "✅ Custom lint script completed"

    - name: Upload formatted files as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: python-files-${{ matrix.python-version }}
        path: |
          c_to_plantuml/
          tests/
          scripts/
          main.py
          run_all_tests.py
          setup.py
          *.py