name: Python Format and Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8

    - name: Check formatting with black
      run: |
        echo "🎨 Checking code formatting..."
        black --check --diff .

    - name: Check import sorting with isort
      run: |
        echo "📦 Checking import sorting..."
        isort --check-only --diff .

    - name: Run linting with flake8
      run: |
        echo "🔍 Running linting..."
        flake8 .

    - name: Format code
      run: |
        echo "🔧 Auto-formatting code..."
        black .
        isort .

    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          git diff
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "style: auto-format code with black and isort

        - Format code with black
        - Sort imports with isort
        - Auto-generated by GitHub Actions"
        git push

    - name: Comment on PR
      if: github.event_name == 'pull_request' && steps.check_changes.outputs.has_changes == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ **Code formatting automatically fixed!**\n\nThis PR had code formatting issues that have been automatically fixed and committed to the branch.\n\n**Changes made:**\n- Formatted code with black\n- Sorted imports with isort\n\nYou can now merge this PR with confidence that all code follows the project\'s formatting standards.'
          })