name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Run all tests
      run: |
        echo "🧪 Running comprehensive test suite..."
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in tests directory:"
        ls -la tests/ || echo "tests directory not found"
        echo "Files in tests/unit directory:"
        ls -la tests/unit/ || echo "tests/unit directory not found"
        echo "Files in tests/feature directory:"
        ls -la tests/feature/ || echo "tests/feature directory not found"
        
        # Try the main test runner first
        python run_all_tests.py || {
          echo "Main test runner failed, trying simple runner..."
          python run_tests_simple.py || {
            echo "Simple test runner also failed, trying direct unittest..."
            python -m unittest discover tests/ -v
          }
        }