name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
        pip install coverage[toml] pytest-cov

    - name: Run all tests with coverage
      run: |
        echo "🧪 Running comprehensive test suite with coverage..."
        
        # Create reports directory
        mkdir -p tests/reports
        
        # Run tests with coverage
        coverage erase
        coverage run -m unittest discover tests -v
        
        # Generate HTML coverage report
        echo "📊 Generating HTML coverage report..."
        coverage html -d tests/reports/coverage-html --title "Code Coverage Report" --show-contexts
        
        # Generate text reports
        coverage report > tests/reports/coverage-summary.txt
        coverage report --show-missing > tests/reports/coverage-detailed.txt
        
        # Create coverage index page
        cat > tests/reports/coverage-index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coverage Reports Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        .card { background: #f5f5f5; padding: 20px; margin: 15px 0; border-radius: 8px; }
        .card h3 { margin-top: 0; color: #333; }
        .card p { color: #666; margin: 10px 0; }
        .btn { background: #007cba; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block; }
        .btn:hover { background: #005a87; }
        .timestamp { color: #888; font-size: 0.9em; }
    </style>
</head>
<body>
    <h1>📊 Code Coverage Reports</h1>
    <p class="timestamp">Generated: $(date)</p>
    
    <div class="card">
        <h3>🌐 Interactive HTML Report</h3>
        <p>Complete coverage report with syntax highlighting and interactive features.</p>
        <a href="coverage-html/index.html" class="btn">View HTML Report</a>
    </div>
    
    <div class="card">
        <h3>📄 Text Reports</h3>
        <p>Coverage summary and detailed missing line information in text format.</p>
        <a href="coverage-summary.txt" class="btn">Summary</a>
        <a href="coverage-detailed.txt" class="btn">Detailed</a>
    </div>
</body>
</html>
EOF
        
        echo "✅ Coverage reports generated in tests/reports/"

    - name: Run example (Shell)
      run: |
        echo "🚀 Running example script..."
        bash run_example.sh
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports-py${{ matrix.python-version }}
        path: tests/reports/
        retention-days: 7