name: Test Auto-Formatting

on:
  workflow_dispatch:

jobs:
  test-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8

    - name: Show current formatting status
      run: |
        echo "🔍 Current formatting status:"
        echo "Black check:"
        black --check --diff . || echo "Black found formatting issues"
        echo "isort check:"
        isort --check-only --diff . || echo "isort found import issues"
        echo "flake8 check:"
        flake8 . || echo "flake8 found linting issues"

    - name: Auto-format code
      run: |
        echo "🔧 Auto-formatting code..."
        black .
        isort .

    - name: Show changes
      run: |
        echo "📝 Changes made:"
        git diff || echo "No changes needed"

    - name: Commit and push changes (if any)
      if: github.event_name == 'workflow_dispatch'
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "📝 Committing formatting changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "test: auto-format code with black and isort"
          git push
          echo "✅ Changes committed and pushed"
        else
          echo "✅ No changes needed"
        fi